@startuml Diagrama de clases

class User{
    - int userId
    - String userName
    - String password
}

interface UserRegister{
    +User create(String userName, String password)
    +User update(User user)
    +delete(int userId)
    +List<User> getUsers()
}

class AdminUser{
    +User createUser(User user)
    +User updateUser(User users)
    +void deleteUser(int idUser)
    +List<User> getAllUsers()
}

class StandardUser{
    +StandardUser view()
    +StandardUser update()
}

class UserController{

}

class UserRegisterImpl{

}

class MainView{

}

class UserLog{
    -String action
    -LocalDateTime timestamp
}



User <|-- AdminUser
User <|-- StandardUser
UserService <.. UserController
UserRegister <|.. UserRegisterImpl
UserRegisterImpl o-- User
UserController <.. MainView
UserRegister <.. UserService
UserRegister <.. AdminUser
User o-- UserLog  

@enduml